# Generated by Django 6.0.6 on 2026-07-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_absurd", "0001_initial_0_4_0"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "source",
                    models.TextField(
                        choices=[("settings", "Settings"), ("admin", "Admin")],
                        default="settings",
                    ),
                ),
                ("alias", models.TextField()),
                ("task", models.TextField()),
                ("queue", models.TextField(blank=True, default="")),
                ("params", models.JSONField(default=dict)),
                ("options", models.JSONField(default=dict)),
                ("cron", models.TextField()),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "django_absurd_scheduledjob",
                "unique_together": {("source", "alias", "name")},
            },
        ),
    ]
