---
services:
  db:
    image: postgres:18.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - beat_pgdata:/var/lib/postgresql

  app:
    build:
      context: ../..
      dockerfile: examples/beat/Dockerfile
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8000:8000"
    environment: &env
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
    volumes: &mounts
      - ./app.py:/app/app.py
      - ../../django_absurd:/src/django_absurd

  worker:
    build:
      context: ../..
      dockerfile: examples/beat/Dockerfile
    command: nanodjango manage app.py absurd_worker --beat
    depends_on:
      - app
    restart: on-failure
    environment: *env
    volumes: *mounts

volumes:
  beat_pgdata:
