# Generated by Django 6.0.6 on 2026-07-08 13:45

from django.db import migrations, models

import django_absurd.pg_cron.validators
import django_absurd.validators


class Migration(migrations.Migration):
    dependencies = [
        ("django_absurd_pg_cron", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="alias",
            field=models.TextField(
                validators=[django_absurd.pg_cron.validators.validate_alias_charset]
            ),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="args",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="kwargs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="name",
            field=models.TextField(
                validators=[django_absurd.pg_cron.validators.validate_name_charset]
            ),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="task",
            field=models.TextField(
                validators=[django_absurd.validators.validate_task_path]
            ),
        ),
    ]
