# Generated by Django 6.0.6 on 2026-07-14 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_absurd_pg_cron",
            "0002_alter_scheduledtask_alias_alter_scheduledtask_args_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="max_attempts",
            field=models.IntegerField(
                blank=True,
                default=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
