# Generated by Django 6.0.6 on 2026-07-14 17:18

from django.db import migrations, models

CREATE_FN = """
CREATE OR REPLACE FUNCTION public.django_absurd_run_scheduled(p_source text, p_alias text, p_name text)
RETURNS void
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
DECLARE
    v public.django_absurd_scheduledtask%ROWTYPE;
    v_params jsonb;
    v_options jsonb;
BEGIN
    SELECT *
      INTO v
      FROM public.django_absurd_scheduledtask
     WHERE source = p_source
       AND alias = p_alias
       AND name = p_name;

    IF NOT FOUND OR NOT v.enabled THEN
        RETURN;
    END IF;

    v_params := jsonb_build_object('args', v.args, 'kwargs', v.kwargs);

    v_options := '{}'::jsonb;
    IF v.max_attempts IS NOT NULL THEN
        v_options := v_options || jsonb_build_object('max_attempts', v.max_attempts);
    END IF;
    IF v.retry_kind != '' THEN
        v_options := v_options || jsonb_build_object('retry_strategy', jsonb_strip_nulls(jsonb_build_object('kind', v.retry_kind, 'base_seconds', v.retry_base_seconds, 'factor', v.retry_factor, 'max_seconds', v.retry_max_seconds)));
    END IF;
    IF v.headers IS NOT NULL THEN
        v_options := v_options || jsonb_build_object('headers', v.headers);
    END IF;
    IF v.cancellation IS NOT NULL THEN
        v_options := v_options || jsonb_build_object('cancellation', v.cancellation);
    END IF;
    IF v.idempotency_key != '' THEN
        v_options := v_options || jsonb_build_object('idempotency_key', v.idempotency_key);
    END IF;

    PERFORM absurd.spawn_task(v.queue, v.task, v_params, v_options);
END;
$$;
"""

RESTORE_FN = """
CREATE OR REPLACE FUNCTION public.django_absurd_run_scheduled(p_source text, p_alias text, p_name text)
RETURNS void
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
DECLARE
    v public.django_absurd_scheduledtask%ROWTYPE;
    v_params jsonb;
    v_options jsonb;
BEGIN
    SELECT *
      INTO v
      FROM public.django_absurd_scheduledtask
     WHERE source = p_source
       AND alias = p_alias
       AND name = p_name;

    IF NOT FOUND OR NOT v.enabled THEN
        RETURN;
    END IF;

    v_params := jsonb_build_object('args', v.args, 'kwargs', v.kwargs);

    v_options := '{}'::jsonb;
    IF v.max_attempts IS NOT NULL THEN
        v_options := v_options || jsonb_build_object('max_attempts', v.max_attempts);
    END IF;
    IF v.retry_strategy IS NOT NULL THEN
        v_options := v_options || jsonb_build_object('retry_strategy', v.retry_strategy);
    END IF;
    IF v.headers IS NOT NULL THEN
        v_options := v_options || jsonb_build_object('headers', v.headers);
    END IF;
    IF v.cancellation IS NOT NULL THEN
        v_options := v_options || jsonb_build_object('cancellation', v.cancellation);
    END IF;
    IF v.idempotency_key != '' THEN
        v_options := v_options || jsonb_build_object('idempotency_key', v.idempotency_key);
    END IF;

    PERFORM absurd.spawn_task(v.queue, v.task, v_params, v_options);
END;
$$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("django_absurd_pg_cron", "0003_alter_scheduledtask_max_attempts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledtask",
            name="retry_strategy",
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="retry_base_seconds",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="retry_factor",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="retry_kind",
            field=models.TextField(
                blank=True,
                choices=[
                    ("exponential", "Exponential"),
                    ("fixed", "Fixed"),
                    ("none", "None"),
                ],
                default="",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="retry_max_seconds",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunSQL(sql=CREATE_FN, reverse_sql=RESTORE_FN),
    ]
