# Generated by Django 6.0.6 on 2026-07-14 18:05

from django.db import migrations, models

import django_absurd.pg_cron.models


class Migration(migrations.Migration):
    dependencies = [
        ("django_absurd_pg_cron", "0005_remove_scheduledtask_cancellation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="queue",
            field=models.TextField(
                blank=True,
                choices=django_absurd.pg_cron.models.get_declared_queue_choices,
                default="",
            ),
        ),
    ]
