# Generated by Django 6.0.7 on 2026-08-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loadtest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccupancyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.UUIDField()),
                ("pid", models.IntegerField()),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
            ],
        ),
    ]
